import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1773417414059 implements MigrationInterface {
    name = 'InitSchema1773417414059'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tenants\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`name\` varchar(150) NOT NULL, \`slug\` varchar(120) NOT NULL, \`domain\` varchar(190) NULL, \`status\` varchar(30) NOT NULL DEFAULT 'active', \`settings_json\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2310ecc5cb8be427097154b18f\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`res_partner\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`entity_type\` varchar(50) NOT NULL, \`name\` varchar(180) NOT NULL, \`legal_name\` varchar(220) NULL, \`is_company\` tinyint(1) NOT NULL DEFAULT '1', \`email\` varchar(190) NULL, \`phone\` varchar(50) NULL, \`website\` varchar(255) NULL, \`logo_url\` varchar(500) NULL, \`description\` text NULL, \`street\` varchar(190) NULL, \`city\` varchar(120) NULL, \`state\` varchar(120) NULL, \`country\` varchar(120) NULL, \`zip\` varchar(30) NULL, \`partner_latitude\` decimal(10,7) NULL, \`partner_longitude\` decimal(10,7) NULL, \`x_partner_role\` varchar(50) NULL, \`x_verification_status\` varchar(30) NOT NULL DEFAULT 'draft', \`nap_json\` json NULL, \`attributes_json\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime NULL, INDEX \`IDX_9c6c51a8e4a3da3b11429bd61e\` (\`entity_type\`), INDEX \`IDX_3600fc88a9a9ac792cd7880c3f\` (\`name\`), INDEX \`IDX_8e658c35692bbb671702755136\` (\`email\`), INDEX \`IDX_5cfeda6a731a27840664a25900\` (\`city\`), INDEX \`IDX_9852fff1a59fdd8f9e0d746666\` (\`x_verification_status\`), INDEX \`idx_partner_geo\` (\`partner_latitude\`, \`partner_longitude\`), INDEX \`idx_partner_tenant_type\` (\`tenant_id\`, \`entity_type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_public_category\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`parent_id\` bigint UNSIGNED NULL, \`name\` varchar(150) NOT NULL, \`slug\` varchar(180) NOT NULL, \`sequence\` int NOT NULL DEFAULT '10', \`meta_title\` varchar(255) NULL, \`meta_description\` text NULL, \`meta_keywords\` varchar(255) NULL, \`description\` text NULL, \`image_url\` varchar(500) NULL, \`active\` tinyint(1) NOT NULL DEFAULT '1', \`show_on_website\` tinyint(1) NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`uq_cat_tenant_slug\` (\`tenant_id\`, \`slug\`), INDEX \`idx_cat_tenant_parent\` (\`tenant_id\`, \`parent_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_template\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`partner_id\` bigint UNSIGNED NOT NULL, \`categ_id\` bigint UNSIGNED NULL, \`listing_type\` varchar(50) NOT NULL, \`vertical_type\` varchar(50) NOT NULL, \`name\` varchar(190) NOT NULL, \`slug\` varchar(220) NOT NULL, \`description_sale\` text NULL, \`list_price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`compare_price\` decimal(12,2) NULL, \`currency_code\` char(3) NOT NULL DEFAULT 'USD', \`type\` varchar(20) NOT NULL DEFAULT 'service', \`sale_ok\` tinyint(1) NOT NULL DEFAULT '1', \`purchase_ok\` tinyint(1) NOT NULL DEFAULT '0', \`default_code\` varchar(100) NULL, \`barcode\` varchar(100) NULL, \`x_service_type\` varchar(50) NULL, \`x_delivery_mode\` varchar(50) NULL, \`x_attributes_json\` json NULL, \`seo_json\` json NULL, \`cta_json\` json NULL, \`cover_image_url\` varchar(500) NULL, \`rating_avg\` decimal(3,2) NOT NULL DEFAULT '0.00', \`is_published\` tinyint(1) NOT NULL DEFAULT '0', \`active\` tinyint(1) NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime NULL, INDEX \`IDX_e37da613604441b746529243cc\` (\`listing_type\`), INDEX \`IDX_3c6edf6a0f66f7647fafe7989b\` (\`name\`), INDEX \`idx_product_partner\` (\`partner_id\`), INDEX \`idx_product_tenant_vertical\` (\`tenant_id\`, \`vertical_type\`), UNIQUE INDEX \`uq_product_tenant_slug\` (\`tenant_id\`, \`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`seo_service\` (\`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`service_scope\` varchar(100) NULL, \`gbp_related\` tinyint(1) NOT NULL DEFAULT '0', \`geo_grid_enabled\` tinyint(1) NOT NULL DEFAULT '0', \`reporting_frequency\` varchar(40) NULL, \`deliverables_json\` json NULL, PRIMARY KEY (\`product_tmpl_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`seo_agency_profile\` (\`partner_id\` bigint UNSIGNED NOT NULL, \`google_partner_status\` varchar(80) NULL, \`service_regions_json\` json NULL, \`tools_json\` json NULL, \`avg_response_time_hours\` decimal(8,2) NULL, PRIMARY KEY (\`partner_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`professional_service\` (\`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`service_modality\` varchar(50) NULL, \`appointment_required\` tinyint(1) NOT NULL DEFAULT '0', \`document_pack_type\` varchar(80) NULL, \`legal_scope_json\` json NULL, PRIMARY KEY (\`product_tmpl_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`professional_firm_profile\` (\`partner_id\` bigint UNSIGNED NOT NULL, \`firm_type\` varchar(80) NULL, \`license_registry\` varchar(180) NULL, \`licensed_regions_json\` json NULL, \`digital_signature_enabled\` tinyint(1) NOT NULL DEFAULT '0', \`document_validation_status\` varchar(30) NOT NULL DEFAULT 'draft', PRIMARY KEY (\`partner_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hardware_store_profile\` (\`partner_id\` bigint UNSIGNED NOT NULL, \`pickup_available\` tinyint(1) NOT NULL DEFAULT '0', \`b2b_enabled\` tinyint(1) NOT NULL DEFAULT '0', \`heavy_logistics_enabled\` tinyint(1) NOT NULL DEFAULT '0', \`warehouse_count\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`partner_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hardware_product\` (\`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`brand\` varchar(120) NULL, \`model\` varchar(120) NULL, \`weight_kg\` decimal(10,3) NULL, \`dimensions_json\` json NULL, \`technical_specs_json\` json NULL, \`is_hazardous\` tinyint(1) NOT NULL DEFAULT '0', \`bulk_price_json\` json NULL, PRIMARY KEY (\`product_tmpl_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`education_provider_profile\` (\`partner_id\` bigint UNSIGNED NOT NULL, \`accreditation_status\` varchar(50) NULL, \`institution_type\` varchar(80) NULL, \`certification_enabled\` tinyint(1) NOT NULL DEFAULT '0', PRIMARY KEY (\`partner_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`course\` (\`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`level\` varchar(50) NULL, \`duration_hours\` decimal(8,2) NULL, \`language_code\` varchar(10) NULL, \`certificate_available\` tinyint(1) NOT NULL DEFAULT '0', \`course_mode\` varchar(40) NULL, PRIMARY KEY (\`product_tmpl_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contractor_service\` (\`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`quote_required\` tinyint(1) NOT NULL DEFAULT '1', \`site_visit_required\` tinyint(1) NOT NULL DEFAULT '0', \`estimated_duration_hours\` decimal(8,2) NULL, \`materials_included\` tinyint(1) NOT NULL DEFAULT '0', \`service_area_json\` json NULL, PRIMARY KEY (\`product_tmpl_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contractor_profile\` (\`partner_id\` bigint UNSIGNED NOT NULL, \`service_area_type\` varchar(50) NULL, \`coverage_radius_km\` decimal(8,2) NULL, \`license_number\` varchar(120) NULL, \`insurance_verified\` tinyint(1) NOT NULL DEFAULT '0', \`emergency_service\` tinyint(1) NOT NULL DEFAULT '0', \`availability_json\` json NULL, PRIMARY KEY (\`partner_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`res_users\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`partner_id\` bigint UNSIGNED NOT NULL, \`username\` varchar(120) NOT NULL, \`email\` varchar(190) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`is_active\` tinyint(1) NOT NULL DEFAULT '1', \`is_email_verified\` tinyint(1) NOT NULL DEFAULT '0', \`kyc_status\` varchar(30) NOT NULL DEFAULT 'draft', \`security_json\` json NULL, \`last_login_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_ef6e7d964f9a36ea8c653cf59d\` (\`tenant_id\`), INDEX \`IDX_1405844d5330b4409e6da9e17d\` (\`partner_id\`), UNIQUE INDEX \`IDX_37af05bfcf5f27072c55c8abc3\` (\`username\`), UNIQUE INDEX \`IDX_5d4ba01d65d17bbc0c44005ad0\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_order\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`order_number\` varchar(60) NOT NULL, \`partner_id\` bigint UNSIGNED NOT NULL, \`x_professional_id\` bigint UNSIGNED NULL, \`status\` varchar(40) NOT NULL DEFAULT 'draft', \`x_service_state\` varchar(40) NULL, \`x_requirement_status\` varchar(40) NULL, \`x_appointment_datetime\` datetime NULL, \`currency_code\` char(3) NOT NULL DEFAULT 'USD', \`amount_untaxed\` decimal(12,2) NOT NULL DEFAULT '0.00', \`amount_tax\` decimal(12,2) NOT NULL DEFAULT '0.00', \`amount_total\` decimal(12,2) NOT NULL DEFAULT '0.00', \`meta_json\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_2c8585a605a5eac27f740b29b1\` (\`status\`), INDEX \`idx_order_partner\` (\`partner_id\`), INDEX \`idx_order_tenant_status\` (\`tenant_id\`, \`status\`), UNIQUE INDEX \`IDX_f1bf060be1d7e1c89a92aa4fb8\` (\`order_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rating_rating\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`reviewer_user_id\` bigint UNSIGNED NOT NULL, \`partner_id\` bigint UNSIGNED NULL, \`product_tmpl_id\` bigint UNSIGNED NULL, \`order_id\` bigint UNSIGNED NULL, \`rating\` decimal(2,1) NOT NULL, \`title\` varchar(190) NULL, \`comment\` text NULL, \`status\` varchar(30) NOT NULL DEFAULT 'published', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_transaction\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`order_id\` bigint UNSIGNED NOT NULL, \`provider\` varchar(60) NOT NULL, \`provider_ref\` varchar(120) NULL, \`status\` varchar(40) NOT NULL, \`amount\` decimal(12,2) NOT NULL, \`currency_code\` char(3) NOT NULL DEFAULT 'USD', \`payload_json\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_product\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`sku\` varchar(120) NOT NULL, \`barcode\` varchar(120) NULL, \`variant_attributes_json\` json NULL, \`price_extra\` decimal(12,2) NOT NULL DEFAULT '0.00', \`active\` tinyint(1) NOT NULL DEFAULT '1', INDEX \`IDX_cf658dd82a5998c5c71f97b6e7\` (\`product_tmpl_id\`), UNIQUE INDEX \`uq_variant_sku\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stock_quant\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`partner_id\` bigint UNSIGNED NOT NULL, \`product_variant_id\` bigint UNSIGNED NOT NULL, \`location_code\` varchar(100) NULL, \`quantity\` decimal(12,2) NOT NULL DEFAULT '0.00', \`reserved_quantity\` decimal(12,2) NOT NULL DEFAULT '0.00', \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`uq_stock_owner_variant_location\` (\`tenant_id\`, \`partner_id\`, \`product_variant_id\`, \`location_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`code\` varchar(50) NOT NULL, \`name\` varchar(100) NOT NULL, UNIQUE INDEX \`IDX_2d49ef9790dc2bcf1722d28d0a\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_role_assignments\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`user_id\` bigint UNSIGNED NOT NULL, \`role_id\` bigint UNSIGNED NOT NULL, \`partner_id\` bigint UNSIGNED NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`uq_user_role_partner\` (\`user_id\`, \`role_id\`, \`partner_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_order_line\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`order_id\` bigint UNSIGNED NOT NULL, \`product_tmpl_id\` bigint UNSIGNED NOT NULL, \`product_variant_id\` bigint UNSIGNED NULL, \`name\` varchar(255) NOT NULL, \`qty\` decimal(12,2) NOT NULL DEFAULT '1.00', \`price_unit\` decimal(12,2) NOT NULL DEFAULT '0.00', \`discount\` decimal(5,2) NOT NULL DEFAULT '0.00', \`subtotal\` decimal(12,2) NOT NULL DEFAULT '0.00', \`line_meta_json\` json NULL, INDEX \`IDX_f932256b6c62babe8b2078f1c7\` (\`order_id\`), INDEX \`IDX_d71c859e76b44429e9ee513aae\` (\`product_tmpl_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`website_filter\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`tenant_id\` bigint UNSIGNED NOT NULL, \`category_id\` bigint UNSIGNED NOT NULL, \`name\` varchar(120) NOT NULL, \`filter_type\` varchar(50) NOT NULL, \`config_json\` json NULL, \`sequence\` int NOT NULL DEFAULT '10', \`is_active\` tinyint(1) NOT NULL DEFAULT '1', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`res_partner\` ADD CONSTRAINT \`FK_3f677fb9eeb73a0ea2c9e6d38f4\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_public_category\` ADD CONSTRAINT \`FK_643006a73ed0bf1ab3b1023e5b1\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_public_category\` ADD CONSTRAINT \`FK_c8836bc8bcd0a630da63043c105\` FOREIGN KEY (\`parent_id\`) REFERENCES \`product_public_category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_template\` ADD CONSTRAINT \`FK_90516bf4cef2b58a124aa6e1f92\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_template\` ADD CONSTRAINT \`FK_f678c8c3a4aa3159d9f9740a504\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_template\` ADD CONSTRAINT \`FK_a006910e773d496fb4a2d7cc8dd\` FOREIGN KEY (\`categ_id\`) REFERENCES \`product_public_category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seo_service\` ADD CONSTRAINT \`FK_4324d96693b898a15f6d5e04ee2\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`seo_agency_profile\` ADD CONSTRAINT \`FK_c59818852e9c77066e3553817ca\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`professional_service\` ADD CONSTRAINT \`FK_87371bcdd9c0fd2eea958dd84eb\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`professional_firm_profile\` ADD CONSTRAINT \`FK_40cb151919a1a036950e45b40d6\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hardware_store_profile\` ADD CONSTRAINT \`FK_55e914676430236b6a7e1d9147e\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hardware_product\` ADD CONSTRAINT \`FK_f7e2325ef91d54da9b4400d7399\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`education_provider_profile\` ADD CONSTRAINT \`FK_82ca5dd3b0efb69f6a9433d1498\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`course\` ADD CONSTRAINT \`FK_624040f8b8529894f7d9ba93a5f\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contractor_service\` ADD CONSTRAINT \`FK_f04031e74754d8a32877c781828\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contractor_profile\` ADD CONSTRAINT \`FK_a132514198aac5343a8c38b8122\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`res_users\` ADD CONSTRAINT \`FK_ef6e7d964f9a36ea8c653cf59d1\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`res_users\` ADD CONSTRAINT \`FK_1405844d5330b4409e6da9e17d3\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_order\` ADD CONSTRAINT \`FK_f554399f985e72877a7169c9b18\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_order\` ADD CONSTRAINT \`FK_727406fefb5970488947b885aef\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_order\` ADD CONSTRAINT \`FK_76d5f6f14fc96b6e97a6a84f558\` FOREIGN KEY (\`x_professional_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` ADD CONSTRAINT \`FK_cbc67a76a32903f846124585468\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` ADD CONSTRAINT \`FK_5ec1686303459ad18c613aa5545\` FOREIGN KEY (\`reviewer_user_id\`) REFERENCES \`res_users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` ADD CONSTRAINT \`FK_81f49bb81d68082d3af87f7409e\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` ADD CONSTRAINT \`FK_4bc342dc52fe5418098804af0ec\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` ADD CONSTRAINT \`FK_7ed26e3935e1968a395b6cbb875\` FOREIGN KEY (\`order_id\`) REFERENCES \`sale_order\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_transaction\` ADD CONSTRAINT \`FK_e7a8b747c958771c350b179760d\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_transaction\` ADD CONSTRAINT \`FK_91163b302301738c73b0b917a1c\` FOREIGN KEY (\`order_id\`) REFERENCES \`sale_order\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_product\` ADD CONSTRAINT \`FK_cf658dd82a5998c5c71f97b6e75\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_quant\` ADD CONSTRAINT \`FK_74fb8a6f08e63b0c457deca89af\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_quant\` ADD CONSTRAINT \`FK_0593908d46745f26b490502f63d\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_quant\` ADD CONSTRAINT \`FK_cde5a03ac904933b33126cb4677\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_product\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role_assignments\` ADD CONSTRAINT \`FK_03eb0e6d5ebfdb266edecb67c7a\` FOREIGN KEY (\`user_id\`) REFERENCES \`res_users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role_assignments\` ADD CONSTRAINT \`FK_daf3517bf1fd13552a06b78dc91\` FOREIGN KEY (\`role_id\`) REFERENCES \`user_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role_assignments\` ADD CONSTRAINT \`FK_e1512102baa707a6a3d324b48b2\` FOREIGN KEY (\`partner_id\`) REFERENCES \`res_partner\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_order_line\` ADD CONSTRAINT \`FK_f932256b6c62babe8b2078f1c7e\` FOREIGN KEY (\`order_id\`) REFERENCES \`sale_order\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_order_line\` ADD CONSTRAINT \`FK_d71c859e76b44429e9ee513aaef\` FOREIGN KEY (\`product_tmpl_id\`) REFERENCES \`product_template\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_order_line\` ADD CONSTRAINT \`FK_8d9c805c3925166a631cab916df\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_product\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`website_filter\` ADD CONSTRAINT \`FK_d091f3f4d60a7317aae54f00873\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`website_filter\` ADD CONSTRAINT \`FK_32afb266c2b615bfdecfb145bf3\` FOREIGN KEY (\`category_id\`) REFERENCES \`product_public_category\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`website_filter\` DROP FOREIGN KEY \`FK_32afb266c2b615bfdecfb145bf3\``);
        await queryRunner.query(`ALTER TABLE \`website_filter\` DROP FOREIGN KEY \`FK_d091f3f4d60a7317aae54f00873\``);
        await queryRunner.query(`ALTER TABLE \`sale_order_line\` DROP FOREIGN KEY \`FK_8d9c805c3925166a631cab916df\``);
        await queryRunner.query(`ALTER TABLE \`sale_order_line\` DROP FOREIGN KEY \`FK_d71c859e76b44429e9ee513aaef\``);
        await queryRunner.query(`ALTER TABLE \`sale_order_line\` DROP FOREIGN KEY \`FK_f932256b6c62babe8b2078f1c7e\``);
        await queryRunner.query(`ALTER TABLE \`user_role_assignments\` DROP FOREIGN KEY \`FK_e1512102baa707a6a3d324b48b2\``);
        await queryRunner.query(`ALTER TABLE \`user_role_assignments\` DROP FOREIGN KEY \`FK_daf3517bf1fd13552a06b78dc91\``);
        await queryRunner.query(`ALTER TABLE \`user_role_assignments\` DROP FOREIGN KEY \`FK_03eb0e6d5ebfdb266edecb67c7a\``);
        await queryRunner.query(`ALTER TABLE \`stock_quant\` DROP FOREIGN KEY \`FK_cde5a03ac904933b33126cb4677\``);
        await queryRunner.query(`ALTER TABLE \`stock_quant\` DROP FOREIGN KEY \`FK_0593908d46745f26b490502f63d\``);
        await queryRunner.query(`ALTER TABLE \`stock_quant\` DROP FOREIGN KEY \`FK_74fb8a6f08e63b0c457deca89af\``);
        await queryRunner.query(`ALTER TABLE \`product_product\` DROP FOREIGN KEY \`FK_cf658dd82a5998c5c71f97b6e75\``);
        await queryRunner.query(`ALTER TABLE \`payment_transaction\` DROP FOREIGN KEY \`FK_91163b302301738c73b0b917a1c\``);
        await queryRunner.query(`ALTER TABLE \`payment_transaction\` DROP FOREIGN KEY \`FK_e7a8b747c958771c350b179760d\``);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` DROP FOREIGN KEY \`FK_7ed26e3935e1968a395b6cbb875\``);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` DROP FOREIGN KEY \`FK_4bc342dc52fe5418098804af0ec\``);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` DROP FOREIGN KEY \`FK_81f49bb81d68082d3af87f7409e\``);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` DROP FOREIGN KEY \`FK_5ec1686303459ad18c613aa5545\``);
        await queryRunner.query(`ALTER TABLE \`rating_rating\` DROP FOREIGN KEY \`FK_cbc67a76a32903f846124585468\``);
        await queryRunner.query(`ALTER TABLE \`sale_order\` DROP FOREIGN KEY \`FK_76d5f6f14fc96b6e97a6a84f558\``);
        await queryRunner.query(`ALTER TABLE \`sale_order\` DROP FOREIGN KEY \`FK_727406fefb5970488947b885aef\``);
        await queryRunner.query(`ALTER TABLE \`sale_order\` DROP FOREIGN KEY \`FK_f554399f985e72877a7169c9b18\``);
        await queryRunner.query(`ALTER TABLE \`res_users\` DROP FOREIGN KEY \`FK_1405844d5330b4409e6da9e17d3\``);
        await queryRunner.query(`ALTER TABLE \`res_users\` DROP FOREIGN KEY \`FK_ef6e7d964f9a36ea8c653cf59d1\``);
        await queryRunner.query(`ALTER TABLE \`contractor_profile\` DROP FOREIGN KEY \`FK_a132514198aac5343a8c38b8122\``);
        await queryRunner.query(`ALTER TABLE \`contractor_service\` DROP FOREIGN KEY \`FK_f04031e74754d8a32877c781828\``);
        await queryRunner.query(`ALTER TABLE \`course\` DROP FOREIGN KEY \`FK_624040f8b8529894f7d9ba93a5f\``);
        await queryRunner.query(`ALTER TABLE \`education_provider_profile\` DROP FOREIGN KEY \`FK_82ca5dd3b0efb69f6a9433d1498\``);
        await queryRunner.query(`ALTER TABLE \`hardware_product\` DROP FOREIGN KEY \`FK_f7e2325ef91d54da9b4400d7399\``);
        await queryRunner.query(`ALTER TABLE \`hardware_store_profile\` DROP FOREIGN KEY \`FK_55e914676430236b6a7e1d9147e\``);
        await queryRunner.query(`ALTER TABLE \`professional_firm_profile\` DROP FOREIGN KEY \`FK_40cb151919a1a036950e45b40d6\``);
        await queryRunner.query(`ALTER TABLE \`professional_service\` DROP FOREIGN KEY \`FK_87371bcdd9c0fd2eea958dd84eb\``);
        await queryRunner.query(`ALTER TABLE \`seo_agency_profile\` DROP FOREIGN KEY \`FK_c59818852e9c77066e3553817ca\``);
        await queryRunner.query(`ALTER TABLE \`seo_service\` DROP FOREIGN KEY \`FK_4324d96693b898a15f6d5e04ee2\``);
        await queryRunner.query(`ALTER TABLE \`product_template\` DROP FOREIGN KEY \`FK_a006910e773d496fb4a2d7cc8dd\``);
        await queryRunner.query(`ALTER TABLE \`product_template\` DROP FOREIGN KEY \`FK_f678c8c3a4aa3159d9f9740a504\``);
        await queryRunner.query(`ALTER TABLE \`product_template\` DROP FOREIGN KEY \`FK_90516bf4cef2b58a124aa6e1f92\``);
        await queryRunner.query(`ALTER TABLE \`product_public_category\` DROP FOREIGN KEY \`FK_c8836bc8bcd0a630da63043c105\``);
        await queryRunner.query(`ALTER TABLE \`product_public_category\` DROP FOREIGN KEY \`FK_643006a73ed0bf1ab3b1023e5b1\``);
        await queryRunner.query(`ALTER TABLE \`res_partner\` DROP FOREIGN KEY \`FK_3f677fb9eeb73a0ea2c9e6d38f4\``);
        await queryRunner.query(`DROP TABLE \`website_filter\``);
        await queryRunner.query(`DROP INDEX \`IDX_d71c859e76b44429e9ee513aae\` ON \`sale_order_line\``);
        await queryRunner.query(`DROP INDEX \`IDX_f932256b6c62babe8b2078f1c7\` ON \`sale_order_line\``);
        await queryRunner.query(`DROP TABLE \`sale_order_line\``);
        await queryRunner.query(`DROP INDEX \`uq_user_role_partner\` ON \`user_role_assignments\``);
        await queryRunner.query(`DROP TABLE \`user_role_assignments\``);
        await queryRunner.query(`DROP INDEX \`IDX_2d49ef9790dc2bcf1722d28d0a\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`uq_stock_owner_variant_location\` ON \`stock_quant\``);
        await queryRunner.query(`DROP TABLE \`stock_quant\``);
        await queryRunner.query(`DROP INDEX \`uq_variant_sku\` ON \`product_product\``);
        await queryRunner.query(`DROP INDEX \`IDX_cf658dd82a5998c5c71f97b6e7\` ON \`product_product\``);
        await queryRunner.query(`DROP TABLE \`product_product\``);
        await queryRunner.query(`DROP TABLE \`payment_transaction\``);
        await queryRunner.query(`DROP TABLE \`rating_rating\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1bf060be1d7e1c89a92aa4fb8\` ON \`sale_order\``);
        await queryRunner.query(`DROP INDEX \`idx_order_tenant_status\` ON \`sale_order\``);
        await queryRunner.query(`DROP INDEX \`idx_order_partner\` ON \`sale_order\``);
        await queryRunner.query(`DROP INDEX \`IDX_2c8585a605a5eac27f740b29b1\` ON \`sale_order\``);
        await queryRunner.query(`DROP TABLE \`sale_order\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d4ba01d65d17bbc0c44005ad0\` ON \`res_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_37af05bfcf5f27072c55c8abc3\` ON \`res_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_1405844d5330b4409e6da9e17d\` ON \`res_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_ef6e7d964f9a36ea8c653cf59d\` ON \`res_users\``);
        await queryRunner.query(`DROP TABLE \`res_users\``);
        await queryRunner.query(`DROP TABLE \`contractor_profile\``);
        await queryRunner.query(`DROP TABLE \`contractor_service\``);
        await queryRunner.query(`DROP TABLE \`course\``);
        await queryRunner.query(`DROP TABLE \`education_provider_profile\``);
        await queryRunner.query(`DROP TABLE \`hardware_product\``);
        await queryRunner.query(`DROP TABLE \`hardware_store_profile\``);
        await queryRunner.query(`DROP TABLE \`professional_firm_profile\``);
        await queryRunner.query(`DROP TABLE \`professional_service\``);
        await queryRunner.query(`DROP TABLE \`seo_agency_profile\``);
        await queryRunner.query(`DROP TABLE \`seo_service\``);
        await queryRunner.query(`DROP INDEX \`uq_product_tenant_slug\` ON \`product_template\``);
        await queryRunner.query(`DROP INDEX \`idx_product_tenant_vertical\` ON \`product_template\``);
        await queryRunner.query(`DROP INDEX \`idx_product_partner\` ON \`product_template\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c6edf6a0f66f7647fafe7989b\` ON \`product_template\``);
        await queryRunner.query(`DROP INDEX \`IDX_e37da613604441b746529243cc\` ON \`product_template\``);
        await queryRunner.query(`DROP TABLE \`product_template\``);
        await queryRunner.query(`DROP INDEX \`idx_cat_tenant_parent\` ON \`product_public_category\``);
        await queryRunner.query(`DROP INDEX \`uq_cat_tenant_slug\` ON \`product_public_category\``);
        await queryRunner.query(`DROP TABLE \`product_public_category\``);
        await queryRunner.query(`DROP INDEX \`idx_partner_tenant_type\` ON \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`idx_partner_geo\` ON \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`IDX_9852fff1a59fdd8f9e0d746666\` ON \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`IDX_5cfeda6a731a27840664a25900\` ON \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e658c35692bbb671702755136\` ON \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`IDX_3600fc88a9a9ac792cd7880c3f\` ON \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c6c51a8e4a3da3b11429bd61e\` ON \`res_partner\``);
        await queryRunner.query(`DROP TABLE \`res_partner\``);
        await queryRunner.query(`DROP INDEX \`IDX_2310ecc5cb8be427097154b18f\` ON \`tenants\``);
        await queryRunner.query(`DROP TABLE \`tenants\``);
    }

}
